stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - wget https://dlcdn.apache.org/subversion/subversion-1.14.2.tar.gz
    - wget https://dlcdn.apache.org//apr/apr-1.7.0.tar.gz
    - wget https://dlcdn.apache.org//apr/apr-util-1.6.1.tar.gz
    - docker build -t svn:1.14.2 .
  after_script:
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag svn:1.14.2 $DOCKER_USERNAME/svn:1.14.2
    - docker images
    - docker push $DOCKER_USERNAME/svn:1.14.2
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
#  rules:
#    - if: $CI_COMMIT_TAG
